package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/magicwubiao/go-magic/internal/agent"
	"github.com/magicwubiao/go-magic/internal/agent/hooks"
	"github.com/magicwubiao/go-magic/internal/approval"
	"github.com/magicwubiao/go-magic/internal/gateway"
	"github.com/magicwubiao/go-magic/internal/provider"
	"github.com/magicwubiao/go-magic/internal/tool"
	"github.com/magicwubiao/go-magic/pkg/config"
	"github.com/magicwubiao/go-magic/pkg/types"
)

// 背景（用户报告）：通过 gateway 发一句"写一个 test.txt 文件"，agent 反复重试
// 直到烧完工具循环，最终回 "AI processing failed: exceeded maximum turns (150)"。
//
// 根因：gateway.processMessage 只造了 context.WithCancel(context.Background())，
// ctx 里没有工作目录，于是审批钩子的 C2 范围放行（isPathWithinWorkdir）永远判否
// → write_file 落到 AskUser → 网关是非交互进程，fail-closed 拒绝 → 模型换个姿势
// 再试，直到 maxTurns。bot 模式（internal/bot/manager.go）早就注入了工作目录，
// 网关这条路径漏了。

// gatewayWorkDir 的三级解析：显式配置 > <working_dir>/gateway > 进程 cwd。
func TestGatewayWorkDirResolution(t *testing.T) {
	t.Run("explicit gateway.working_dir wins", func(t *testing.T) {
		explicit := filepath.Join(t.TempDir(), "my-sandbox")
		cfg := &config.Config{}
		cfg.WorkingDir = t.TempDir()
		cfg.Gateway.WorkingDir = explicit

		if got := gatewayWorkDir(cfg); got != explicit {
			t.Fatalf("gatewayWorkDir = %q, want the explicit %q", got, explicit)
		}
	})

	t.Run("defaults to <working_dir>/gateway", func(t *testing.T) {
		base := t.TempDir()
		cfg := &config.Config{}
		cfg.WorkingDir = base

		want := filepath.Join(base, "gateway")
		if got := gatewayWorkDir(cfg); got != want {
			t.Fatalf("gatewayWorkDir = %q, want %q", got, want)
		}
	})

	t.Run("falls back to process cwd", func(t *testing.T) {
		cwd, err := os.Getwd()
		if err != nil {
			t.Skipf("Getwd unavailable: %v", err)
		}
		if got := gatewayWorkDir(&config.Config{}); got != cwd {
			t.Fatalf("gatewayWorkDir = %q, want cwd %q", got, cwd)
		}
		if got := gatewayWorkDir(nil); got != cwd {
			t.Fatalf("gatewayWorkDir(nil) = %q, want cwd %q", got, cwd)
		}
	})
}

// 网关 agent 的配置接线：沙箱目录（含建目录）、审批策略都要从主配置来，
// 而不是留在写死的默认值上。
func TestGatewayApplyConfigWiresWorkspaceAndApprovalPolicy(t *testing.T) {
	t.Setenv("GO_MAGIC_HOME", t.TempDir())

	base := t.TempDir()
	cfg := &config.Config{}
	cfg.WorkingDir = base
	cfg.Approval = &config.ApprovalConfig{Strategy: "auto"}

	h := newEmptyGatewayAgentHandler()
	h.applyConfig(cfg)

	wantDir := filepath.Join(base, "gateway")
	if h.workDir != wantDir {
		t.Fatalf("handler workDir = %q, want %q", h.workDir, wantDir)
	}
	if fi, err := os.Stat(wantDir); err != nil || !fi.IsDir() {
		t.Fatalf("sandbox dir was not created: stat(%q) err=%v", wantDir, err)
	}
	if h.registry == nil {
		t.Fatal("registry not rebuilt by applyConfig")
	}
	if h.systemPrompt == "" {
		t.Error("system prompt not generated by applyConfig")
	}
	if h.approvalMgr == nil {
		t.Fatal("approval manager not wired from config")
	}
	if got := h.approvalMgr.GetConfig().Strategy; got != approval.StrategyAutoApprove {
		t.Errorf("approval strategy = %q, want %q (config approval.strategy must reach the gateway)", got, approval.StrategyAutoApprove)
	}
	if h.cfg != cfg {
		t.Error("config snapshot not retained on the handler")
	}

	// nil 配置必须是惰性 no-op（懒加载路径可能拿到 nil）。
	h.applyConfig(nil)
	if h.workDir != wantDir {
		t.Errorf("applyConfig(nil) clobbered workDir: %q", h.workDir)
	}
}

// scriptedTool 是个名字可变、永远成功的工具。用它而不是 echoTool 连打，是因为
// agent 的循环检测会把"同一个工具被调用到 sameToolLimit(3) 次"当作死循环提前
// 中止（并转向"请给个总结"），那样就测不到 max_turns 了。
type scriptedTool struct{ name string }

func (t *scriptedTool) Name() string        { return t.name }
func (t *scriptedTool) Description() string { return "test tool " + t.name }
func (t *scriptedTool) Schema() map[string]interface{} {
	return map[string]interface{}{"type": "object"}
}

func (t *scriptedTool) Execute(context.Context, map[string]interface{}) (interface{}, error) {
	return "ok", nil
}

// 工具循环上限接入主配置：agent.max_turns 必须真的作用到网关 agent 上。
// 用一个"永远请求工具"的 provider 驱动，断言循环在配置值处停下。
func TestGatewayAgentHonorsConfiguredMaxTurns(t *testing.T) {
	t.Setenv("GO_MAGIC_HOME", t.TempDir())

	const wantTurns = 3

	// 每轮换一个工具名：避开循环检测（见 scriptedTool 的注释）。
	toolNames := []string{"alpha", "beta", "gamma", "delta"}
	registry := tool.NewRegistry()
	for _, n := range toolNames {
		registry.Register(&scriptedTool{name: n})
	}

	calls := make([]*provider.ChatResponse, wantTurns+2)
	for i := range calls {
		calls[i] = &provider.ChatResponse{
			Content: "working",
			ToolCalls: []types.ToolCall{
				{
					ID:        fmt.Sprintf("c%d", i),
					Name:      toolNames[i%len(toolNames)],
					Arguments: map[string]interface{}{},
				},
			},
		}
	}

	cfg := &config.Config{}
	cfg.Agent.MaxTurns = wantTurns

	h := &gatewayAgentHandler{
		provider: &stubToolCallProvider{calls: calls},
		registry: registry,
		cfg:      cfg,
		agents:   make(map[string]*agent.Agent),
	}

	ag, err := h.getOrCreateAgent("user-1")
	if err != nil {
		t.Fatalf("getOrCreateAgent error: %v", err)
	}

	_, err = ag.RunConversation(context.Background(), "never finishes")
	if err == nil {
		t.Fatal("expected the tool loop to hit the configured cap")
	}
	want := "exceeded maximum turns (3)"
	if !strings.Contains(err.Error(), want) {
		t.Fatalf("error = %v, want it to contain %q (config max_turns not applied)", err, want)
	}
}

// 网关 agent 的审批钩子必须是"非交互"的：从终端启动 gateway 时 stdin 恰好是
// tty，但控制台前没人会点"同意"——钩子不能去读 stdin，而要立刻 fail-closed。
func TestGatewayAgentApprovalHookIsNonInteractive(t *testing.T) {
	t.Setenv("GO_MAGIC_HOME", t.TempDir())

	registry := tool.NewRegistry()
	registry.Register(&scriptedTool{name: "alpha"})

	h := &gatewayAgentHandler{
		provider: &stubToolCallProvider{},
		registry: registry,
		agents:   make(map[string]*agent.Agent),
	}

	ag, err := h.getOrCreateAgent("user-1")
	if err != nil {
		t.Fatalf("getOrCreateAgent error: %v", err)
	}
	hook := ag.GetApprovalHook()
	if hook == nil {
		t.Fatal("agent has no approval hook")
	}
	if !hook.IsNonInteractive() {
		t.Fatal("gateway approval hook must be marked non-interactive (it would block on stdin)")
	}
}

// 注入后的 ctx 必须真的能让工作目录内的 write_file 自动放行，而不只是"ctx 里有
// 这个值"：只要有人把 turnContext 的注入删掉或改成别的键，这里就会红。
func TestGatewayTurnContextEnablesScopedFileWriteApproval(t *testing.T) {
	// NewManager 会写 GetMagicHome()/approval，用临时目录隔离。
	t.Setenv("GO_MAGIC_HOME", t.TempDir())

	workDir := t.TempDir()
	h := &gatewayAgentHandler{workDir: workDir}

	ctx := h.turnContext(context.Background(), gateway.Message{
		UserID:   "user-1",
		Platform: "wecom",
	})

	if got := tool.WorkDirFromContext(ctx); got != workDir {
		t.Fatalf("work dir not injected into ctx: got %q, want %q", got, workDir)
	}
	if got := tool.SessionIDFromContext(ctx); got != "user-1" {
		t.Errorf("session id not injected into ctx: got %q, want %q", got, "user-1")
	}

	mgr, err := approval.NewManager(nil) // strategy=smart，与生产默认一致
	if err != nil {
		t.Fatalf("approval.NewManager error: %v", err)
	}
	// 审批结果与模式是异步落盘的，必须先 flush 再让 t.TempDir() 删目录
	// （t.Cleanup 是 LIFO，这里晚注册所以先执行）。
	t.Cleanup(mgr.FlushPendingSaves)
	hook := agent.NewApprovalHookWithManager(mgr)

	_, dec, err := hook.BeforeTool(ctx, &hooks.ToolCallHookRequest{
		ToolName: "write_file",
		ToolArgs: map[string]interface{}{"path": "test.txt", "content": "hello"},
	})
	if err != nil {
		t.Fatalf("BeforeTool error: %v", err)
	}
	if dec.Action != hooks.HookActionContinue {
		t.Fatalf("write_file inside the gateway work dir was not auto-approved: action=%v, reason=%q",
			dec.Action, dec.Reason)
	}
}
