package skills

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Pattern represents a detected usage pattern
type Pattern struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Tools        []string `json:"tools"`         // Tools used in order
	ToolSequence []string `json:"tool_sequence"` // Ordered sequence of tool calls
	Frequency    int      `json:"frequency"`     // How many times observed
	Confidence   float64  `json:"confidence"`    // Pattern quality score
	ExampleTasks []string `json:"example_tasks"` // Where this pattern was seen
}

// EnhancedAutoCreator builds on the basic auto-creator with pattern mining
// This is the core of System 6: Skill Self-Evolution
type EnhancedAutoCreator struct {
	baseDir      string
	patterns     []Pattern
	skillCount   int
	minFrequency int // Minimum occurrences to generate skill
}

// NewEnhancedAutoCreator creates an enhanced skill auto-creator
func NewEnhancedAutoCreator(baseDir string) *EnhancedAutoCreator {
	skillsDir := filepath.Join(baseDir, "auto_skills")
	os.MkdirAll(skillsDir, 0755)

	return &EnhancedAutoCreator{
		baseDir:      skillsDir,
		patterns:     make([]Pattern, 0),
		minFrequency: 2, // Generate skill after seeing pattern twice
	}
}

// AnalyzeToolSequence analyzes a sequence of tool calls for patterns
func (e *EnhancedAutoCreator) AnalyzeToolSequence(task string, tools []string) {
	if len(tools) < 3 {
		return // Need at least 3 tools to form a meaningful pattern
	}

	// Look for subsequences that repeat across tasks
	for i := 0; i < len(tools)-2; i++ {
		subsequence := tools[i : i+3]

		// Check if we've seen this pattern before
		patternKey := strings.Join(subsequence, " → ")
		found := false

		for pIdx := range e.patterns {
			existingKey := strings.Join(e.patterns[pIdx].ToolSequence, " → ")
			if existingKey == patternKey {
				e.patterns[pIdx].Frequency++
				e.patterns[pIdx].ExampleTasks = append(e.patterns[pIdx].ExampleTasks, task)
				found = true
				break
			}
		}

		if !found {
			// New pattern detected
			e.patterns = append(e.patterns, Pattern{
				Name:         fmt.Sprintf("Pattern-%d", len(e.patterns)+1),
				Description:  fmt.Sprintf("Detected sequence: %s", patternKey),
				Tools:        subsequence,
				ToolSequence: subsequence,
				Frequency:    1,
				Confidence:   0.5,
				ExampleTasks: []string{task},
			})
		}
	}
}

// AnalyzeFullSession analyzes a complete session for skill generation
func (e *EnhancedAutoCreator) AnalyzeFullSession(sessionData map[string]interface{}) {
	// Extract task description
	taskDesc, _ := sessionData["task"].(string)

	// Extract tool sequence
	var toolSequence []string
	if tools, ok := sessionData["tool_sequence"].([]string); ok {
		toolSequence = tools
	}

	// Analyze for patterns
	e.AnalyzeToolSequence(taskDesc, toolSequence)

	// Check if any pattern is now ready for skill generation
	for _, pattern := range e.patterns {
		if pattern.Frequency >= e.minFrequency && pattern.Confidence >= 0.6 {
			e.GenerateSkillFromPattern(pattern)
		}
	}
}

// GenerateSkillFromPattern generates a skill file from a detected pattern
func (e *EnhancedAutoCreator) GenerateSkillFromPattern(pattern Pattern) error {
	skillID := fmt.Sprintf("auto-%s-%d", pattern.Name, time.Now().Unix())
	skillDir := filepath.Join(e.baseDir, skillID)
	os.MkdirAll(skillDir, 0755)

	// Generate skill metadata
	skillMeta := map[string]interface{}{
		"id":           skillID,
		"name":         fmt.Sprintf("Automated %s", pattern.Name),
		"description":  pattern.Description,
		"author":       "cortex-auto",
		"created_at":   time.Now().Format(time.RFC3339),
		"level":        "Level 1",
		"pattern_tools": pattern.Tools,
		"frequency":    pattern.Frequency,
		"examples":     pattern.ExampleTasks,
	}

	metaJSON, _ := json.MarshalIndent(skillMeta, "", "  ")
	os.WriteFile(filepath.Join(skillDir, "meta.json"), metaJSON, 0644)

	// Generate SKILL.md - the main skill file using progressive disclosure
	skillMD := e.generateSkillMarkdown(pattern, skillMeta)
	os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(skillMD), 0644)

	e.skillCount++

	// Log skill generation
	logContent := fmt.Sprintf("[%s] Generated skill '%s' from pattern seen %d times\n",
		time.Now().Format(time.RFC3339), pattern.Name, pattern.Frequency)
	os.WriteFile(filepath.Join(e.baseDir, "generation.log"), []byte(logContent), 0644)

	return nil
}

// generateSkillMarkdown generates progressive disclosure markdown
func (e *EnhancedAutoCreator) generateSkillMarkdown(pattern Pattern, meta map[string]interface{}) string {
	var sb strings.Builder

	// Level 0: Header + brief description (disclosed first)
	sb.WriteString(fmt.Sprintf("# %s\n\n", meta["name"].(string)))
	sb.WriteString(fmt.Sprintf("**Auto-generated by Cortex Agent** | Pattern seen %d times\n\n", pattern.Frequency))
	sb.WriteString(fmt.Sprintf("## What this skill does\n\n%s\n\n", pattern.Description))

	// Level 1: Full instructions (disclosed when user actually uses the skill)
	sb.WriteString("---\n\n")
	sb.WriteString("## Level 1: Complete Usage Guide\n\n")
	sb.WriteString("### Tool Sequence\n\n")
	sb.WriteString("This skill uses the following tool sequence:\n\n")
	for i, tool := range pattern.ToolSequence {
		sb.WriteString(fmt.Sprintf("%d. `%s`\n", i+1, tool))
	}

	sb.WriteString("\n### How to Use\n\n")
	sb.WriteString("When you need to perform this task:\n")
	sb.WriteString("1. Call the first tool with appropriate parameters\n")
	sb.WriteString("2. Use results from previous step as input to next tool\n")
	sb.WriteString("3. Continue until the sequence is complete\n\n")

	sb.WriteString("### Example Tasks\n\n")
	for _, example := range pattern.ExampleTasks {
		sb.WriteString(fmt.Sprintf("- %s\n", example))
	}

	// Level 2: Reference material (disclosed for complex tasks)
	sb.WriteString("\n---\n\n")
	sb.WriteString("## Level 2: Reference and Tips\n\n")
	sb.WriteString("### Common Pitfalls\n\n")
	sb.WriteString("- Make sure each tool call completes successfully before proceeding\n")
	sb.WriteString("- Verify intermediate results before moving to complex operations\n")
	sb.WriteString("- If a step fails, consider alternative approaches or ask for clarification\n\n")

	sb.WriteString("### Optimization Tips\n\n")
	sb.WriteString("- Consider parallel execution for independent sub-tasks\n")
	sb.WriteString("- Cache intermediate results when appropriate\n")
	sb.WriteString("- Document any deviations from the standard pattern\n\n")

	sb.WriteString("\n---\n\n")
	sb.WriteString("*This skill was auto-generated by Cortex Agent's pattern recognition system.*\n")
	sb.WriteString("*It will be improved and refined as the pattern is used more frequently.*\n")

	return sb.String()
}

// GetPatterns returns all detected patterns
func (e *EnhancedAutoCreator) GetPatterns() []Pattern {
	return e.patterns
}

// GetGeneratedSkills returns all auto-generated skills
func (e *EnhancedAutoCreator) GetGeneratedSkills() []string {
	var skills []string

	entries, err := os.ReadDir(e.baseDir)
	if err != nil {
		return skills
	}

	for _, entry := range entries {
		if entry.IsDir() && strings.HasPrefix(entry.Name(), "auto-") {
			skills = append(skills, entry.Name())
		}
	}

	return skills
}

// GetStats returns statistics about pattern detection and skills
func (e *EnhancedAutoCreator) GetStats() map[string]interface{} {
	return map[string]interface{}{
		"patterns_detected":  len(e.patterns),
		"skills_generated":   e.skillCount,
		"min_frequency":      e.minFrequency,
		"pending_patterns":   e.countPendingPatterns(),
	}
}

func (e *EnhancedAutoCreator) countPendingPatterns() int {
	count := 0
	for _, p := range e.patterns {
		if p.Frequency < e.minFrequency {
			count++
		}
	}
	return count
}

// SetMinFrequency sets the minimum frequency threshold for skill generation
func (e *EnhancedAutoCreator) SetMinFrequency(freq int) {
	e.minFrequency = freq
}

// ExportPatterns exports all patterns for analysis
func (e *EnhancedAutoCreator) ExportPatterns(path string) error {
	data, err := json.MarshalIndent(e.patterns, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0644)
}
